# Encoding algorithm
publicKeyAlgorithm: RSA
publicKeyTransformation: RSA/ECB/PKCS1Padding
secretKeyAlgorithm: DESede
secretKeyTransformation: DESede/CBC/PKCS5Padding
secretSeed: some secret bytes

# should be at least 512
keySize: 1024

# message to encode
message: Hello World!

# servers to use
keysmithServer: http://localhost:8080
messengerServer: http://localhost:8080
